### ISSUE TITLE
hand-test v0.5.0, update status messages in docs

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1279]
A hand-testing plan. While we're doing this, we should update anything in the docs that shows status messages printed out by mrjob, since these have been cleaned up (see #1044).

Things to update in docs:
 - [x] examples of status messages
 - [x] add `boss` to `guides/cmd.rst`
 - [x] fold `guides/emr-tools.rst` into `guides/cmd.rst`
 - [x] mention `mrjob-x.y` command in `guides/cmd.rst`
 - [x] note in `whats-new.rst` that some mrjob subcommands have been renamed
 - [x] note changes in "job flow" options and subcommands (#1082)

Things to hand-test:
 - [x] bootstrap cookbook:
  - [x] installing ujson from PyPI
  - [x] yum installing a python27-numpy
  - [x] apt-get installing python-pip and using it to install ujson on 2.4.2 AMI (failed!)
 - [x] two-step job (test fetching counters):
  - [x] default setup (no SSH, no pooling)
    - [x] 2.4.11 AMI (steps log fetching is broken on 2.4.2, see #1287)
    - [x] 3.11.0 AMI
    - [x] 4.4.0 AMI
  - [x] SSH + pooling
    - [x] 2.4.11 AMI
    - [x] 3.11.0 AMI
    - [x] 4.4.0 AMI
  - [x] Hadoop runner (inside above AMIs)
    - [x] Hadoop 1 (inside 2.4.11)
    - [x] Hadoop 2 (inside 3.11.0)
    - [x] Hadoop 2 (inside 4.4.0)
 - [x] fetch probable cause of error (multiple nodes):
   - [x] 2.4.9 AMI (failed! see #1288)
   - [x] 3.x AMI
   - [x] 4.x AMI
   - [x] Hadoop 1 (2.x AMI)
   - [x] Hadoop 2 (3.x AMI)
 - [x] bootstrap_python_packages (test on glob, like Yelp uses it)
  - [x] 2.4.2 AMI (test using `pip` on Python 2.6, see #1285)
  - [x] 2.4.9 AMI
  - [x] 3.11.0 AMI
  - [x] 4.4.0 AMI
 - [x] hadoop_extra_args and hadoop_streaming_jar (just verify they get passed through):
  - [x] EMR runner (any AMI)
  - [x] Hadoop runner (any Hadoop version)
 - [x] hand-test mrjob subcommands:
   - [x] audit-emr-usage
   - [x] `mrjob boss j-CLUSTERID vmstat` (see #1282)
   - [x] create-cluster
   - [x] report-long-jobs
   - [x] terminate-cluster
   - [x] s3-tmpwatch (was broken, see #1290)
   - [x] terminate-idle-clusters (was broken, see #1290)
 - [x] create brand new AWS account, run a job on EMR with default settings

**Comment by davidmarin** [comment]
Also, this fits better in #1250, but should stop referencing tools by their module name, and suggest `max_hours_idle` as an alternative to `mrjob terminate-idle-clusters`.

**Comment by davidmarin** [comment]
Ugh, you can't do `python -m pip install ...` on Python 2.6; see #1285.

**Comment by davidmarin** [comment]
Also: "Unexpected option hadoop_log_dir"

**Comment by davidmarin** [comment]
Fixed --hadoop-log-dir switch (see above).

**Comment by davidmarin** [comment]
Done!
