### ISSUE TITLE
local mode refactor testing checklist

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1623]
Some things not to forget to test:

 - [x] unit tests of sorting, to replace the old tests of self._invoke_sort()
 - [x] move unit tests of sim-runner functionality to `test_sim.py`
 - [x] ensure that we can pass input files to a job that doesn't take arguments (#567)
 - [x] test that files in sim distributed cache are user executable (#1619)

**Comment by davidmarin** [comment]
Merged `sim-runner-tests` branch into `master`.
