### ISSUE TITLE
Complete release checklist for v0.4.1

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#752]
- update `mrjob.__version__` in `mrjob/__init__.py`
- [x] `pyflakes` and `pep8`ify
- [x] do final code review of diff from last release
- [x] update `CHANGES.txt`
- [x] update `whats-new.rst`
- [x] check `git log` for any contributors we missed
- [x] verify that docs build properly
- [x] push to `master`, tag on GitHub
- [x] upload to PyPI
- [x] build docs and upload them to PyPI
- [x] update `mrjob.__version__` in `master` to be the next dev version
